### ISSUE TITLE
Слив в master веток meta и modules

### ISSUE THREAD

**Issue by Rabbitlancer** [XorTechDevTeam/ignition#27]
- [x] документировать классы ветки `modules`
- [x] документировать классы ветки `meta`
- [x] дождаться выполнения #25 
- [x] слить все в `master`
- [x] удалить `modules` и `meta`
- [x] вставить Doxyfile в `master`
- [x] создать ветки по фичам
